/** 与文档 10 节对齐的业务错误码 */
export const ErrorCodes = {
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  DIARY_NOT_FOUND: 'DIARY_NOT_FOUND',
  DIARY_CONFLICT: 'DIARY_CONFLICT',
  DIARY_TOO_LONG: 'DIARY_TOO_LONG',
  SYNC_FAILED: 'SYNC_FAILED',
  WEATHER_API_FAILED: 'WEATHER_API_FAILED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVER_ERROR: 'SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
